Repository HydrologicEngineeringCenter/HEC-FDA, pull requests merged in 2021-10, with the labels that each got.

#100 add metadata for NuGet Packages of Statistics and Utilities
  Statistics/Statistics.csproj
  Utilities/Utilities.csproj
Labels: CI/CD

#108 Bug/general code cleanup
  Model/ISingleSample.cs
  Utilities/Utilities.csproj
  View/GeoTech/FailureFunctionEditor.xaml
  View/View.csproj
  ViewModel/ViewModel.csproj
  ViewModelTests/ViewModelTests.csproj
  lib/gdal_csharp.dll
  lib/gdal_wrap.dll
  lib/gdalconst_csharp.dll
  lib/gdalconst_wrap.dll
  lib/ogr_csharp.dll
  lib/ogr_wrap.dll
  lib/osr_csharp.dll
  lib/osr_wrap.dll
Labels: invalid

#155 creating a unit test to trap a bug with parametric bootstrap fixes #154
  Statistics/Distributions/IDistributionExtensions.cs
  StatisticsTests/Distributions/ParametricBootstrap.cs
Labels: bug
