Repository HydrologicEngineeringCenter/HEC-FDA, pull requests merged in 2023-02, with the labels that each got.

#763 remove bad validation logic. Add column mappings to match MuncieNSI. …
  fda-model-test/unittests/structures/InventoryShould.cs
  fda-model/structures/Inventory.cs
Labels: bug

#778 needed to validate impact area stage damage Fixes #777
  fda-model/stageDamage/ImpactAreaStageDamage.cs
Labels: bug

#795 Fixes #794
  fda-model/metrics/AlternativeComparisonReportResults.cs
  fda-model/metrics/AlternativeResults.cs
  fda-model/metrics/ConsequenceDistributionResult.cs
  fda-model/metrics/ConsequenceDistributionResults.cs
  fda-model/metrics/ImpactAreaScenarioResults.cs
  fda-model/metrics/ScenarioResults.cs
  fda-model/structures/DeterministicStructure.cs
  fda-model/structures/Inventory.cs
  fda-model/structures/OccupancyType.cs
  fda-model/structures/SampledStructureParameters.cs
  fda-model/structures/Structure.cs
  fda-model/utilities/IntegerConstants.cs
Labels: documentation

#796 Fixing "impact area row" name bug.
  ViewModel/AggregatedStageDamage/StageDamageCurve.cs
Labels: bug

#785 642 handle reprojection of sis not in the same projection as the hydraulics
  ViewModel/Inventory/InventoryColumnSelectionsVM.cs
  ViewModel/Inventory/InventoryElement.cs
  fda-model-test/integrationtests/TractableStageDamageTests.cs
  fda-model-test/unittests/StageDamageShould.cs
  fda-model-test/unittests/hydraulics/HydraulicProfileShould.cs
  fda-model-test/unittests/structures/InventoryShould.cs
  fda-model/hydraulics/HydraulicDataset.cs
  fda-model/hydraulics/HydraulicProfile.cs
  fda-model/stageDamage/ImpactAreaStageDamage.cs
  fda-model/structures/Inventory.cs
  fda-model/structures/Structure.cs
Labels: enhancement
